title:            Mapping Early-Modern Venezuela
email:            andreina@ucsb.edu
description:      A digital humanities project about Venezuela
author:           Andreina Soto
baseurl:          "/mapping-venezuela.github.io" # Leave this alone if this is your main site (i.e. username.github.io). If instead this is a site for a project, e.g. username.github.io/
url:              "http://Andreina-Soto.github.io/mapping-venezuela" # or http://username.github.io/mycleverproject if it is a project site, or http://mylovelydomainname.com if you have a domain, and so on.

collections:
  pages:
    output: true
    permalink: /:name

# Social Profiles
twitter_username:  SeguNina
github_username:   AndreinaSoto
facebook_username:

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
